# Setup
title:        Computer Graphics Project
tagline:      Improving the raytracer
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Florian Cassayre
  url:        https://florian.cassayre.me

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
